FROM datamachines/cudnn_tensorflow_opencv:11.3.1_2.9.1_3.4.16-20220815

MAINTAINER datamachines

# Setting up working directory 
RUN mkdir /advan
WORKDIR /advan

CMD ["echo", "\"Hello Advantecher\""]